### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by JoeryVandenBosch** [almenscorner/intunecd-monitor#2]
Hi, 
I was able to get the frontend running, however i noticed that when i add users to the enterprise application with the admin role (custom role i have created in the app registration as per your documentation intunecd_admin) i'm getting the Internal Server error 500. When i remove the rights i can browse to the application offcourse with no rights but the page is loading. When i change back the rights to the custom role i immediately get the 500 error.
Is this behaviour you have already seen?

Thank you.

**Comment by almenscorner** [comment]
Hi,

I have not encountered this issue before, the role assignments are working as expected in my environment. Can you send some screenshots of the setup of the Enterprise/App registration?

You can also check the "Log stream" output on the App Service when trying to connect with a user assigned to the role.

**Comment by JoeryVandenBosch** [comment]
Hi here are some screenshots

![image](https://user-images.githubusercontent.com/38684871/197156638-bac508d3-e48d-4f02-98d0-3a1ad4f2d0a9.png)
![image](https://user-images.githubusercontent.com/38684871/197159325-7fd70e9d-29f6-402d-9652-eab710e46f59.png)
![image](https://user-images.githubusercontent.com/38684871/197159466-054fa627-ada2-48fd-8c61-637909b42bec.png)
![image](https://user-images.githubusercontent.com/38684871/197159772-ed75e9b7-526c-4954-99c1-04d416e9fb49.png)

**Comment by JoeryVandenBosch** [comment]
Hi, here is the output of the log stream:

2022-10-21T09:32:17  Welcome, you are now connected to log-streaming service.

Starting Log Tail -n 10 of existing logs ----
/appsvctmp/volatile/logs/runtime/dea22748612f6ddf6c615c8ae5194a914535c59c4d5183694a727d26bf00d159.log
2022-10-21T09:19:36.025634151Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/css/material-dashboard.css?v=3.0.2 HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65296"
2022-10-21T09:19:36.049153822Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/js/core/bootstrap.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65300"
2022-10-21T09:19:36.054808539Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/js/core/popper.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65301"
2022-10-21T09:19:36.077435906Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/js/plugins/perfect-scrollbar.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65295"
2022-10-21T09:19:36.080562716Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/css/nucleo-icons.css HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65304"
2022-10-21T09:19:36.089524443Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/css/nucleo-svg.css HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65302"
2022-10-21T09:19:36.100553276Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/js/plugins/smooth-scrollbar.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65296"
2022-10-21T09:19:36.116813525Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/assets/js/material-dashboard.min.js?v=3.0.2 HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65300"
2022-10-21T09:19:36.161723959Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:36 +0000] "GET /static/manifest.json HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/settings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65306"
2022-10-21T09:19:37.926249563Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:19:37 +0000] "GET /sw.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/sw.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:65300"

/appsvctmp/volatile/logs/runtime/f511c8d3d98795dcf868cef18a7a63c086a403f0c8eed3692aa4ff64d95f0fe9.log
2022-10-21T09:19:03.020047647Z: [ERROR]      pipelines = get_pipeline_data(app_config.DEVOPS_ORG_NAME, app_config.DEVOPS_PROJECT_NAME, token)
2022-10-21T09:19:03.020054447Z: [ERROR]    File "/intunecd/app/devops_api.py", line 15, in get_pipeline_data
2022-10-21T09:19:03.020061447Z: [ERROR]      data = json.loads(devops_data.text)
2022-10-21T09:19:03.020067547Z: [ERROR]    File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
2022-10-21T09:19:03.020074447Z: [ERROR]      return _default_decoder.decode(s)
2022-10-21T09:19:03.020080747Z: [ERROR]    File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
2022-10-21T09:19:03.020088047Z: [ERROR]      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2022-10-21T09:19:03.020094447Z: [ERROR]    File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
2022-10-21T09:19:03.020101447Z: [ERROR]      raise JSONDecodeError("Expecting value", s, err.value) from None
2022-10-21T09:19:03.020108347Z: [ERROR]  json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

Ending Log Tail of existing logs ---
Starting Live Log Stream ---
2022-10-21T09:32:37.037682689Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/css/nucleo-svg.css HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49249"
2022-10-21T09:32:37.049363679Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/js/core/bootstrap.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49252"
2022-10-21T09:32:37.052607276Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/css/nucleo-icons.css HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49250"
2022-10-21T09:32:37.056778473Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/css/material-dashboard.css?v=3.0.2 HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49251"
2022-10-21T09:32:37.078676055Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/js/core/popper.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49254"
2022-10-21T09:32:37.082050052Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/js/plugins/perfect-scrollbar.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49253"
2022-10-21T09:32:37.093256743Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:37 +0000] "GET /static/assets/js/plugins/smooth-scrollbar.min.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49249"

2022-10-21T09:32:38.794940042Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:38 +0000] "GET /sw.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/sw.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49249"
2022-10-21T09:32:39.083978405Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:39 +0000] "GET /auth/signin-oidc?code=0.AUsAaveFSxwHrkqTC7vdpC1OLp-bF12gwGdNtdQmHPW9G0RLAII.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P8fCp4gEi84GLru326fCZqdXDBpHLFUpqCXUU8hQzQURcJr3XGxx6fwX32qtJtJkZsfCBiyKfrykhQW1lH3zIvd8mWPLmwI6n0AaEmuB9JgaA83Ba0nPjimIS21tcgzlZzGxTaPaWcG_9zjq9b92npTUpOir0zIFbJar9Htpk9mnZNfvymy3UDzaoT0SCo-cPdQacJM8HGa5kQ5OAdee3qdnADdMl7faZN3xl9elD2bK1vTmukZpI8mEahWXC8fTIWSHo5E9AZpOlH_so68URI4pftfVq-Gq1obIaJjUhfFyynp4Q086QHXHXB1KIV-NIbbg-vm3UzuuFwRvxhSVGR891pj4xQP3FaQgp50sAYsG8KgoZq8Iz9aW0zyoyKwTEMv2C5dAdhSOuZ2lcBiA0fCV080W-AYREF-J0pkF6yB4mGvMM55MEYZrgQKLpiWyzKbV1GxqOwvDRE48wBrjDeuOHiFbUsu-UR1cCFEk_WY3dUIn8j9taKf0Xggj5BDMr8tDWi358uwt9qiLGB4gMkEXHWqC1tChVLTlnrIjSSA59-l1JLQdFawNESEY4Rne8doLWMsrWc-Vs-dQVVhR-LLEu5X2C_662lYoRmKtMUk40dtNeK1EXAwPYsXl8cIV1-9VwJ1IOoUYe-xrNjzS-TySaO0N5B_p7RoXVT5Z2RJyQvYTcZhxgNkVTcymIZdO7W7fnF_VnRQii-_h3nVOvV33XuUTgPxytivWy6L0PZS7DK0e8rlLdevIwTYOqeuhF8f4c3nkrYGdjOU04vhMeusHFVzDCEIYlWSruGs3r4TOkAuGn9JfOc4wcucKEmgOs0ihjRclENbv-FSz-lI4sZBv58kgl0FivTjs6prY2o97uBuiZ6PNAPjhLdqgmhYvshCUoFgTluLSk11oWdyYzOsZ7GXhGKF0L492sBpH4c&client_info=eyJ1aWQiOiIyNTUwYzNhMC0wNjVkLTQxM2UtOTUyNS1lZmUzYmFjZWFlYTkiLCJ1dGlkIjoiNGI4NWY3NmEtMDcxYy00YWFlLTkzMGItYmJkZGE0MmQ0ZTJlIn0&state=uhrvOmoPVDxCGeiQ&session_state=ce340ee7-0c6e-40a3-b707-0a540d400a37 HTTP/1.1" 302 216 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49253"
2022-10-21T09:32:39.760125551Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:39 +0000] "GET /home HTTP/1.1" 500 290 "https://intunecd-devtest.azurewebsites.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49253"
2022-10-21T09:32:41.498484860Z: [INFO]  172.16.3.1 - - [21/Oct/2022:09:32:41 +0000] "GET /sw.js HTTP/1.1" 304 0 "https://intunecd-devtest.azurewebsites.net/sw.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "81.83.10.167:49253"

2022-10-21T09:32:39.738469568Z: [ERROR]  [2022-10-21 09:32:39,733] ERROR in app: Exception on /home [GET]
2022-10-21T09:32:39.739784767Z: [ERROR]  Traceback (most recent call last):
2022-10-21T09:32:39.739806567Z: [ERROR]    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
2022-10-21T09:32:39.739815867Z: [ERROR]      response = self.full_dispatch_request()
2022-10-21T09:32:39.739824167Z: [ERROR]    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-10-21T09:32:39.739832367Z: [ERROR]      rv = self.handle_user_exception(e)
2022-10-21T09:32:39.739839967Z: [ERROR]    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-10-21T09:32:39.739848167Z: [ERROR]      rv = self.dispatch_request()
2022-10-21T09:32:39.739855667Z: [ERROR]    File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
2022-10-21T09:32:39.739863967Z: [ERROR]      return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-10-21T09:32:39.739871867Z: [ERROR]    File "/intunecd/app/decorators.py", line 38, in wrap
2022-10-21T09:32:39.739879667Z: [ERROR]      return f(*args, **kwargs)
2022-10-21T09:32:39.739887367Z: [ERROR]    File "/intunecd/app/decorators.py", line 67, in wrap
2022-10-21T09:32:39.739894767Z: [ERROR]      return f(*args, **kwargs)
2022-10-21T09:32:39.739902267Z: [ERROR]    File "/intunecd/app/routes.py", line 90, in home
2022-10-21T09:32:39.739910067Z: [ERROR]      pipelines = get_pipeline_data(app_config.DEVOPS_ORG_NAME, app_config.DEVOPS_PROJECT_NAME, token)
2022-10-21T09:32:39.739917967Z: [ERROR]    File "/intunecd/app/devops_api.py", line 15, in get_pipeline_data
2022-10-21T09:32:39.739925667Z: [ERROR]      data = json.loads(devops_data.text)
2022-10-21T09:32:39.739933467Z: [ERROR]    File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
2022-10-21T09:32:39.739940767Z: [ERROR]      return _default_decoder.decode(s)
2022-10-21T09:32:39.739978567Z: [ERROR]    File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
2022-10-21T09:32:39.739988167Z: [ERROR]      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2022-10-21T09:32:39.739995567Z: [ERROR]    File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
2022-10-21T09:32:39.740003067Z: [ERROR]      raise JSONDecodeError("Expecting value", s, err.value) from None
2022-10-21T09:32:39.740009967Z: [ERROR]  json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

**Comment by almenscorner** [comment]
Looks like it's having issue getting your Azure DevOps project or org. I'm able to replicate the issue if I configure a DevOps org which does not exist on the App Service. Is the `DEVOPS_ORG_NAME` and `DEVOPS_PROJECT_NAME` correctly configured?

**Comment by almenscorner** [comment]
Happy it worked :)
