### ISSUE TITLE
"Internal Server Error", caused by failure connecting to Azure DevOps

### ISSUE THREAD

**Issue by Skorfulose** [almenscorner/intunecd-monitor#20]
Hi Tobias,

I hope you are doing well. I guess the new job keeps you quite busy. But maybe you can help me and have an idea about the following:

I am currently going through first/initial setup of intunecd-monitor. I created the app registration, including the Azure DevOps permission, with admin consent granted.
When trying to open intunecd-monitor, I receive an "Internal Server Error". I checked the log and this is the relevant section:
```
2023-05-26T05:49:27.747919979Z Region configured (None) != region detected ('westeurope')
2023-05-26T05:49:27.822162876Z Region configured (None) != region detected ('westeurope')
2023-05-26T05:49:28.055973693Z [2023-05-26 05:49:28,055] ERROR in app: Exception on /home [GET]
2023-05-26T05:49:28.056006164Z Traceback (most recent call last):
2023-05-26T05:49:28.056011884Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
2023-05-26T05:49:28.056016383Z     response = self.full_dispatch_request()
2023-05-26T05:49:28.056020360Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
2023-05-26T05:49:28.056024368Z     rv = self.handle_user_exception(e)
2023-05-26T05:49:28.056028155Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
2023-05-26T05:49:28.056032232Z     rv = self.dispatch_request()
2023-05-26T05:49:28.056036350Z   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
2023-05-26T05:49:28.056040498Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-05-26T05:49:28.056044555Z   File "/intunecd/app/decorators.py", line 38, in wrap
2023-05-26T05:49:28.056048693Z     return f(*args, **kwargs)
2023-05-26T05:49:28.056052690Z   File "/intunecd/app/decorators.py", line 67, in wrap
2023-05-26T05:49:28.056056938Z     return f(*args, **kwargs)
2023-05-26T05:49:28.056061106Z   File "/intunecd/app/routes.py", line 124, in home
2023-05-26T05:49:28.056065254Z     pipelines = get_pipeline_data(
2023-05-26T05:49:28.056069442Z   File "/intunecd/app/devops_api.py", line 15, in get_pipeline_data
2023-05-26T05:49:28.056073579Z     data = json.loads(devops_data.text)
2023-05-26T05:49:28.056077697Z   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
2023-05-26T05:49:28.056081444Z     return _default_decoder.decode(s)
2023-05-26T05:49:28.056084800Z   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
2023-05-26T05:49:28.056088918Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-05-26T05:49:28.056092965Z   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
2023-05-26T05:49:28.056097644Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-05-26T05:49:28.056102012Z json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)
```

Obviously the JSON decode fails because the  `devops_data` retrieved [here](https://github.com/almenscorner/intunecd-monitor/blob/095565ff8667539b2365e552b153907672c22801/app/devops_api.py#L11) in `app/devops_api.py` is empty.

I checked by manually opening the URL (filled with the actual variable values) in my browser
`https://dev.azure.com/{devops_org_name}/{devops_project_name}/_apis/build/builds?queryOrder=queueTimeDescending&maxBuildsPerDefinition=1`
and it works fine. Valid JSON response returned with the expected pipeline content returned!
 So `{devops_org_name}` and `{devops_project_name}` values are definitely correct. I triple-checked the Azure template / App service configuration.

I suspected the delegated auth to ADO fails. But I also triple-checked the intunecd-monitor app registration and it looks perfectly fine. And in Azure AD Sign-in logs I can see non-interactive user sign-ins from the intunecd-monitor app registration to Azure DevOps succeed:

![2023-05-26_09-09-49](https://github.com/almenscorner/intunecd-monitor/assets/735359/7feff682-d5cf-40ab-9731-3a9959d72521)

Any idea? My own troubleshooting is exhausted here... 😄

**Comment by almenscorner** [comment]
Hi,

Yeah it's been some busy months ;)

Thanks for all the details provided here, are you able to share the JSON returned when you manually check `https://dev.azure.com/{devops_org_name}/{devops_project_name}/_apis/build/builds?queryOrder=queueTimeDescending&maxBuildsPerDefinition=1`?

**Comment by Skorfulose** [comment]
Here's the linted JSON with a lot of REDACTED IDs etc. 😉
As far as I can tell, the necessary keys expected by the get_pipeline_data() function are there.

```
{
    "count": 2,
    "value": [
        {
            "_links": {
                "self": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Builds/1144601"
                },
                "web": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_build/results?buildId=1144601"
                },
                "sourceVersionDisplayUri": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1144601/sources"
                },
                "timeline": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1144601/Timeline"
                },
                "badge": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/status/8556"
                }
            },
            "properties": {},
            "tags": [],
            "validationResults": [],
            "plans": [
                {
                    "planId": "b283e73f-44e0-4940-a4cf-e7c961908437"
                }
            ],
            "triggerInfo": {
                "ci.sourceBranch": "refs/heads/configs-2023-05-17-13-37",
                "ci.sourceSha": "2de3e1083b83698f87a81025155721a4bfafc452",
                "ci.message": "Updated configurations",
                "ci.triggerRepository": "d9081f51-0288-40aa-98e1-01314d39bdab"
            },
            "id": 1144601,
            "buildNumber": "20230517.228",
            "status": "completed",
            "result": "succeeded",
            "queueTime": "2023-05-17T13:37:42.9759822Z",
            "startTime": "2023-05-17T13:37:50.9110395Z",
            "finishTime": "2023-05-17T13:39:32.1761374Z",
            "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Builds/1144601",
            "definition": {
                "drafts": [],
                "id": 8556,
                "name": "IntuneCD-REDACTEDpoc",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Definitions/8556?revision=2",
                "uri": "vstfs:///Build/Definition/8556",
                "path": "\\",
                "type": "build",
                "queueStatus": "enabled",
                "revision": 2,
                "project": {
                    "id": "REDACTED-e51f-414f-9d3e-d1e860f45131",
                    "name": "Workplace",
                    "description": "(created 8/29/2017)\n\nWorkspace for multiple Workplace-related sub-topics (projects, initiatives, engineering topics, ...)",
                    "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/projects/REDACTED-e51f-414f-9d3e-d1e860f45131",
                    "state": "wellFormed",
                    "revision": 56013908,
                    "visibility": "private",
                    "lastUpdateTime": "2019-06-07T11:54:29Z"
                }
            },
            "buildNumberRevision": 228,
            "project": {
                "id": "REDACTED-e51f-414f-9d3e-d1e860f45131",
                "name": "Workplace",
                "description": "(created 8/29/2017)\n\nWorkspace for multiple Workplace-related sub-topics (projects, initiatives, engineering topics, ...)",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/projects/REDACTED-e51f-414f-9d3e-d1e860f45131",
                "state": "wellFormed",
                "revision": 56013908,
                "visibility": "private",
                "lastUpdateTime": "2019-06-07T11:54:29Z"
            },
            "uri": "vstfs:///Build/Build/1144601",
            "sourceBranch": "refs/heads/configs-2023-05-17-13-37",
            "sourceVersion": "2de3e1083b83698f87a81025155721a4bfafc452",
            "queue": {
                "id": 8187,
                "name": "Azure Pipelines",
                "pool": {
                    "id": 90,
                    "name": "Azure Pipelines",
                    "isHosted": true
                }
            },
            "priority": "normal",
            "reason": "individualCI",
            "requestedFor": {
                "displayName": "Project Collection Build Service (DEVOPS_ORG_NAME_REDACTED)",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/7b5f3421-90fc-4b57-b6b1-40af5855f8e3",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/svc.YWVlN2I1MDgtMDQ5My00M2Y3LWIzM2YtZDRhM2RkNmU5Njg0OkJ1aWxkOjNhM2MyZTYzLWU2NzctNDVlMi04NWI0LWVhNzlkZTZjNGU2MQ"
                    }
                },
                "id": "7b5f3421-90fc-4b57-b6b1-40af5855f8e3",
                "uniqueName": "Build\\3a3c2e63-e677-45e2-85b4-ea79de6c4e61",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/svc.YWVlN2I1MDgtMDQ5My00M2Y3LWIzM2YtZDRhM2RkNmU5Njg0OkJ1aWxkOjNhM2MyZTYzLWU2NzctNDVlMi04NWI0LWVhNzlkZTZjNGU2MQ",
                "descriptor": "svc.YWVlN2I1MDgtMDQ5My00M2Y3LWIzM2YtZDRhM2RkNmU5Njg0OkJ1aWxkOjNhM2MyZTYzLWU2NzctNDVlMi04NWI0LWVhNzlkZTZjNGU2MQ"
            },
            "requestedBy": {
                "displayName": "Microsoft.VisualStudio.Services.TFS",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/00000002-0000-8888-8000-000000000000",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
                    }
                },
                "id": "00000002-0000-8888-8000-000000000000",
                "uniqueName": "00000002-0000-8888-8000-000000000000@2c895908-04e0-4952-89fd-54b0046d6288",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED",
                "descriptor": "s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
            },
            "lastChangedDate": "2023-05-17T13:39:32.57Z",
            "lastChangedBy": {
                "displayName": "Microsoft.VisualStudio.Services.TFS",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/00000002-0000-8888-8000-000000000000",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
                    }
                },
                "id": "00000002-0000-8888-8000-000000000000",
                "uniqueName": "00000002-0000-8888-8000-000000000000@2c895908-04e0-4952-89fd-54b0046d6288",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED",
                "descriptor": "s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
            },
            "orchestrationPlan": {
                "planId": "b283e73f-44e0-4940-a4cf-e7c961908437"
            },
            "logs": {
                "id": 0,
                "type": "Container",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1144601/logs"
            },
            "repository": {
                "id": "d9081f51-0288-40aa-98e1-01314d39bdab",
                "type": "TfsGit",
                "name": "IntuneCD-REDACTEDpoc",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/Workplace/_git/IntuneCD-REDACTEDpoc",
                "clean": null,
                "checkoutSubmodules": false
            },
            "retainedByRelease": false,
            "triggeredByBuild": null,
            "appendCommitMessageToRunName": true
        },
        {
            "_links": {
                "self": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Builds/1007524"
                },
                "web": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_build/results?buildId=1007524"
                },
                "sourceVersionDisplayUri": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1007524/sources"
                },
                "timeline": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1007524/Timeline"
                },
                "badge": {
                    "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/status/7792"
                }
            },
            "properties": {},
            "tags": [],
            "validationResults": [],
            "plans": [
                {
                    "planId": "95355d17-160f-4b87-b970-61cde97f9827"
                }
            ],
            "triggerInfo": {},
            "id": 1007524,
            "buildNumber": "20230131.1",
            "status": "completed",
            "result": "succeeded",
            "queueTime": "2023-01-31T16:41:21.3624503Z",
            "startTime": "2023-01-31T16:41:30.6095777Z",
            "finishTime": "2023-01-31T16:41:40.730338Z",
            "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Builds/1007524",
            "definition": {
                "drafts": [],
                "id": 7792,
                "name": "Intune Config-as-Code",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/Definitions/7792?revision=1",
                "uri": "vstfs:///Build/Definition/7792",
                "path": "\\",
                "type": "build",
                "queueStatus": "enabled",
                "revision": 1,
                "project": {
                    "id": "REDACTED-e51f-414f-9d3e-d1e860f45131",
                    "name": "Workplace",
                    "description": "(created 8/29/2017)\n\nWorkspace for multiple Workplace-related sub-topics (projects, initiatives, engineering topics, ...)",
                    "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/projects/REDACTED-e51f-414f-9d3e-d1e860f45131",
                    "state": "wellFormed",
                    "revision": 56013908,
                    "visibility": "private",
                    "lastUpdateTime": "2019-06-07T11:54:29Z"
                }
            },
            "buildNumberRevision": 1,
            "project": {
                "id": "REDACTED-e51f-414f-9d3e-d1e860f45131",
                "name": "Workplace",
                "description": "(created 8/29/2017)\n\nWorkspace for multiple Workplace-related sub-topics (projects, initiatives, engineering topics, ...)",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/projects/REDACTED-e51f-414f-9d3e-d1e860f45131",
                "state": "wellFormed",
                "revision": 56013908,
                "visibility": "private",
                "lastUpdateTime": "2019-06-07T11:54:29Z"
            },
            "uri": "vstfs:///Build/Build/1007524",
            "sourceBranch": "refs/heads/main",
            "sourceVersion": "6819235dc04fa473eb0ef9a5acb668692784bf70",
            "queue": {
                "id": 8187,
                "name": "Azure Pipelines",
                "pool": {
                    "id": 90,
                    "name": "Azure Pipelines",
                    "isHosted": true
                }
            },
            "priority": "normal",
            "reason": "manual",
            "requestedFor": {
                "displayName": "REDACTED",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/REDACTED-fe1f-4871-8ee7-f9c6df3564c9",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED"
                    }
                },
                "id": "REDACTED-fe1f-4871-8ee7-f9c6df3564c9",
                "uniqueName": "REDACTED@REDACTED.com",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED",
                "descriptor": "aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED"
            },
            "requestedBy": {
                "displayName": "REDACTED",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/REDACTED-fe1f-4871-8ee7-f9c6df3564c9",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED"
                    }
                },
                "id": "REDACTED-fe1f-4871-8ee7-f9c6df3564c9",
                "uniqueName": "REDACTED@REDACTED.com",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED",
                "descriptor": "aad.OTJkOTlmNjctYjcwNC03NWE1LTgyMTUtOTFREDACTED"
            },
            "lastChangedDate": "2023-01-31T16:41:42Z",
            "lastChangedBy": {
                "displayName": "Microsoft.VisualStudio.Services.TFS",
                "url": "https://spsprodweu1.vssps.visualstudio.com/REDACTED-0493-43f7-b33f-d4a3dd6e9684/_apis/Identities/00000002-0000-8888-8000-000000000000",
                "_links": {
                    "avatar": {
                        "href": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
                    }
                },
                "id": "00000002-0000-8888-8000-000000000000",
                "uniqueName": "00000002-0000-8888-8000-000000000000@2c895908-04e0-4952-89fd-54b0046d6288",
                "imageUrl": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED",
                "descriptor": "s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwREDACTED"
            },
            "orchestrationPlan": {
                "planId": "95355d17-160f-4b87-b970-61cde97f9827"
            },
            "logs": {
                "id": 0,
                "type": "Container",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/REDACTED-e51f-414f-9d3e-d1e860f45131/_apis/build/builds/1007524/logs"
            },
            "repository": {
                "id": "959b2f9f-df28-4b36-8d45-966a4ee0c618",
                "type": "TfsGit",
                "name": "Intune Config-as-Code",
                "url": "https://dev.azure.com/DEVOPS_ORG_NAME_REDACTED/Workplace/_git/Intune%20Config-as-Code",
                "clean": null,
                "checkoutSubmodules": false
            },
            "retainedByRelease": false,
            "triggeredByBuild": null,
            "appendCommitMessageToRunName": true
        }
    ]
}
```

**Comment by almenscorner** [comment]
Looks fine, I'm trying to replicate but haven't been able to so far, even if there is no pipelines in the  project all works fine. I could add a null check before it tries to load the JSON but I really want to figure out why it gives a null response

**Comment by almenscorner** [comment]
What's the response if you run this manually?

```python
import requests
from msal import ConfidentialClientApplication, PublicClientApplication

AUTHORITY = "https://login.microsoftonline.com/"
SCOPE = ["https://graph.microsoft.com/.default"]

def obtain_accesstoken_app(TENANT_NAME, CLIENT_ID, CLIENT_SECRET):
    app = ConfidentialClientApplication(
        client_id=CLIENT_ID,
        client_credential=CLIENT_SECRET,
        authority=AUTHORITY + TENANT_NAME,
    )

    token = None

    try:
        # Check if token is already cached
        token = app.acquire_token_silent(SCOPE, account=None)

        # If not, get a new token
        if not token:
            token = app.acquire_token_for_client(scopes=SCOPE)
            if not token:
                raise Exception("No token returned")

    except Exception as e:
        raise Exception("Error obtaining access token: " + str(e))

    return token

devops_org_name = 'org_name'
devops_project_name = 'project_name'
token = obtain_accesstoken_app('tenant_name', 'client_id', 'client_secret')

requests.get(  # Use token to call downstream service
        f'https://dev.azure.com/{devops_org_name}/{devops_project_name}/_apis/build/builds?queryOrder=queueTimeDescending&maxBuildsPerDefinition=1',
        headers={'Authorization': 'Bearer ' + token['access_token']},
    )
```

**Comment by Skorfulose** [comment]
The `response.text` when I run the above manually is the ADO sign-in page 🤨

![image](https://github.com/almenscorner/intunecd-monitor/assets/735359/79298ae3-0634-4781-b538-5c7b376dd6c3)

access_token properly decodes on [jwt.io](https://jwt.io/). And as noted earlier, the AAD Sign-in logs show the successful auth. So why the sign-in page now?!

**Comment by Skorfulose** [comment]
I think I might have a pointer to the issue:
Our DevOps instance is connected to a different AAD tenant.

My user identity and the app registration are in tenant A.
The ADO instance is connected to tenant B.
My tenant A user can log in to ADO in tenant B because of federation I think. 

I know we have another ADO instance connected to our main tenant, so I will request a project there for verification.

**Comment by almenscorner** [comment]
Were you able to test the above @Skorfulose or confirm the issues is tied to the ADO instance being in another tenant?

**Comment by Skorfulose** [comment]
Sorry, I didn’t manage to get testing done before going on leave. Will continue troubleshooting end of next week.

**Comment by almenscorner** [comment]
Thank you for verifying @Skorfulose 👍, I will keep this in mind in future releases!
